var test = require('tape')
var indexOfLastOutline = require('../../lib/utils/index-of-last-outline.js')

test('indexOfLastOutline()', function (t) {
  t.equal(indexOfLastOutline(['C4']), 0)
  t.equal(indexOfLastOutline(['C4', 'D4']), 0)
  t.equal(indexOfLastOutline(['C4', 'B3']), 0)
  t.equal(indexOfLastOutline(['C4', 'D4', 'E4']), 0)
  t.equal(indexOfLastOutline(['C4', 'D4', 'C4']), 1)
  t.equal(indexOfLastOutline(['C4', 'D4', 'C4', 'C4']), 1)
  t.equal(indexOfLastOutline(['C4', 'C4', 'C4', 'C4']), 0)
  t.equal(indexOfLastOutline(['C4', 'D4', 'E4', 'F4', 'E4']), 3)
  t.equal(indexOfLastOutline(['C4', 'D4', 'E4', 'F4', 'E4', 'E4', 'D4']), 3)
  t.equal(indexOfLastOutline(['C4', 'D4', 'E4', 'F4', 'E4', 'E4', 'D4', 'C4']), 3)
  t.equal(indexOfLastOutline(['C4', 'B3', 'A3', 'G3', 'C4']), 3)
  t.equal(indexOfLastOutline(['C4', 'B3', 'A3', 'G3', 'C4', 'D4']), 3)
  t.equal(indexOfLastOutline(['C4', 'B3', 'A3', 'G3', 'C4', 'D4', 'E4']), 3)
  t.equal(indexOfLastOutline(['C4', 'B3', 'A3', 'G3', 'C4', 'D4', 'E4', 'E4']), 3)
  t.equal(indexOfLastOutline(['C4', 'B3', 'A3', 'G3', 'C4', 'D4', 'E4', 'E4', 'D4']), 6)
  t.end()
})
